# Generated by Django 2.0.7 on 2018-07-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180729_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestedevent',
            old_name='text',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='suggestedevent',
            name='section_id',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='suggestedevent',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='suggestedevent',
            name='contact_person',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='suggestedevent',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='suggestedevent',
            name='url_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestedevent',
            name='venue',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
