# Generated by Django 2.0.7 on 2018-07-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180731_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedevent',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='suggestedevent',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
