# Generated by Django 2.1 on 2018-08-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
